### ISSUE TITLE
can't connect through a bluetooth proxy

### ISSUE THREAD

**Issue by stefdewilde** [chrisrosset/mamaroo-mqtt#7]
Hey @chrisrosset 

I want to install this docker, but I can't seem to connect my mamaroo through the bluetooth of my HA.

I use a ESP32 as a bluetooth proxy. It does recognize it:

[11:14:24][VV][esp32_ble_tracker:369]: Parse Result:
[11:14:24][VV][esp32_ble_tracker:386]:   Address: 20:D7:78:D7:A9:7C (PUBLIC)
[11:14:24][VV][esp32_ble_tracker:388]:   RSSI: -69
[11:14:24][VV][esp32_ble_tracker:389]:   Name: 'Blimp1.0'
[11:14:24][VV][esp32_ble_tracker:391]:   TX Power: 2
[11:14:24][VV][esp32_ble_tracker:397]:   Ad Flag: 6
[11:14:24][VV][esp32_ble_tracker:400]:   Service UUID: 622D0100-2416-0FA7-E132-2F1495CC2CE0
[11:14:24][VV][esp32_ble_tracker:414]:   Service data:
[11:14:24][VV][esp32_ble_tracker:415]:     UUID: 0xFFFF
[11:14:24][VV][esp32_ble_tracker:416]:     Data: 34.61.6D.61.00 (5)
[11:14:24][VV][esp32_ble_tracker:419]: Adv data: 02.01.06.11.07.E0.2C.CC.95.14.2F.32.E1.A7.0F.16.24.00.01.2D.62.08.16.FF.FF.34.61.6D.61.00.09.09.42.6C.69.6D.70.31.2E.30.02.0A.00 (43)
[11:14:24][V][bluetooth_proxy:033]: Proxying packet from Blimp1.0 - 20:D7:78:D7:A9:7C. RSSI: -69 dB

But I get these in my docker log:

Traceback (most recent call last):
  File "/app/mamaroo_mqtt.py", line 245, in <module>
    main()
  File "/app/mamaroo_mqtt.py", line 235, in main
    subprocess.call(['bluetoothctl','disconnect', args.MAC], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1935, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['bluetoothctl', 'disconnect', '20:D7:78:D7:A9:7C']' timed out after 10 seconds
2023-03-24 10:19:49,824 INFO Configuration = Namespace(prefix='homeassistant', broker='core-mosquitto', username=None, password=None, serial=None, verbose=False, MAC='20:D7:78:D7:A9:7C')

Anyway to fix this?

**Comment by chrisrosset** [comment]
Hey! I've never used a Bluetooth proxy before. As far as I can tell from the docs I found on ESPHome, Home Assistant can use a proxy over WiFi instead of using a USB adapter.

This project is not a Home Assistant integration though so it doesn't know anything about your proxy. It connects directly to a Bluetooth adapter and posts data over MQTT to your HA instance.

Realistically, the code would have to be rewritten to be an actual HA integration to support this.
